### ISSUE TITLE
Weird green dude 

### ISSUE THREAD

**Issue by shawnanastasio** [KingRandomGuy/CurryCraft-1.7.10#4]
I updated and now there's this weird green dude harrassing me. He took my wife and kids.

**Comment by KingRandomGuy** [comment]
That is an intended feature

**Comment by drsn0w** [comment]
assign wontfix tag here

**Comment by shawnanastasio** [comment]
IS MY WIFE WITH YOU???

**Comment by theracermaster** [comment]
yes

**Comment by KingRandomGuy** [comment]
The weird green dude ate your wife

**Comment by drsn0w** [comment]
Assign wontfix tag please
-rms
